/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'Usuario' at '9/12/16 9:55' with Gradle 3.2.1
 *
 * @author Usuario, @date 9/12/16 9:55
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }

    public static void main( String[] args )
    {
        System.out.println( "Hola Mundo!" );
    }
}
